<a href="https://colab.research.google.com/github/rafaelhenrique2009/An-lise-de-dados/blob/main/3_Eccomerce_limpeza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importe as bibliotecas necessárias
import os #  interagir com o sistema de arquivos (pastas, caminhos, etc).
import pandas as pd # manipulação de dados em tabelas (dataframes).
import matplotlib.pyplot as plt # Criação de gráficos
import seaborn as sns # Criação de gráficos
import numpy as np # manipulação de dados e fórmulas matemáticas

In [ ]:
# Autenticar a pasta do GoogleDrive
from google.colab import drive, files
drive.mount('/content/drive')
os.chdir('/content/drive/MyDrive/Eccomerce/Olist')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Criar as variáveis para ler tabelas
df_orders = pd.read_csv("olist_orders_dataset.csv", sep=',')
df_order_items = pd.read_csv("olist_order_items_dataset.csv", sep=',')
df_products = pd.read_csv("olist_products_dataset.csv", sep=',')
df_customer = pd.read_csv("olist_customers_dataset.csv", sep=',')
df_payments = pd.read_csv("olist_order_payments_dataset.csv", sep=',')
df_sellers = pd.read_csv("olist_sellers_dataset.csv", sep=',')
df_geolocation = pd.read_csv("olist_geolocation_dataset.csv", sep=',')

**Tabela: products**

In [ ]:
# Mostrar as 5 primeiras linhas
df_products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [ ]:
# Número de linhas e colunas
df_products.shape

(32951, 9)

In [ ]:
# Nomes das variáveis
df_products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [ ]:
# Informações sobre os tipos de dados
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

**Tabela: sellers**

In [ ]:
# Mostrar as 5 primeiras linhas
df_sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [ ]:
# Número de linhas e colunas
df_sellers.shape

(3095, 4)

In [ ]:
# Nomes das variáveis
df_sellers.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [ ]:
# Informações sobre os tipos de dados
df_sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

**Tabela: geolocation**

In [ ]:
# Mostrar as 5 primeiras linhas
df_geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [ ]:
# Número de linhas e colunas
df_geolocation.shape

(1000163, 5)

In [ ]:
# Nomes das variáveis
df_geolocation.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='object')

In [ ]:
# Informações sobre os tipos de dados
df_geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

**Tabela: customer**

In [ ]:
# Mostrar as 5 primeiras linhas
df_customer.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [ ]:
# Número de linhas e colunas
df_customer.shape

(99441, 5)

In [ ]:
# Nomes das variáveis
df_customer.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [ ]:
# Informações sobre os tipos de dados
df_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

**Tabela: payments**

In [ ]:
# Mostrar as 5 primeiras linhas
df_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [ ]:
# Número de linhas e colunas
df_payments.shape

(103886, 5)

In [ ]:
# Nomes das variáveis
df_payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [ ]:
# Informações sobre os tipos de dados
df_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

##**Limpeza de dados**

Esta etapa é a mais importante e porque os dados precisam estar limpos antes de começar qualquer análise. Se os dados não forem limpos minuciosamente, os resultados serão imprecisos podendo causar erros na hora de tomar decisões estratégicas. A tradução de todo o dataset é importante já que nem todos os stakeholders falam inglês.

As etapas de limpeza serão:

- Renomear colunas;
- Remover espaços;
- Remover duplicatas;
- Padronizar maiúsculas e minúsculas;
- Mudar os tipos dos atributos se precisar;
- Tratar dados faltantes.

###**Tabela: olist_orders_dataset**

In [ ]:
# Mostrar as 5 primeiras linhas
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [ ]:
# Número de linhas e colunas
df_orders.shape

(99441, 8)

In [ ]:
# Nomes das variáveis
df_orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [ ]:
# Informações sobre os tipos de dados
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [ ]:
# Criar uma cópia
df_orders_copy = df_orders.copy()

In [ ]:
# Remover espaços iniciais e finais de todas as linhas
df_orders_copy.columns = df_orders_copy.columns.str.strip()

In [ ]:
# Colunas da tabela
df_orders_copy.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [ ]:
# Renomeando colunas
df_orders_copy.rename(columns=
 {'order_id':'ordem_id',
  'customer_id':'cliente_id',
  'order_status':'status_do_pedido',
  'order_purchase_timestamp':'data_da_compra',
  'order_approved_at':'data_da_aprovacao',
  'order_delivered_carrier_date':'data_de_envio',
  'order_delivered_customer_date': 'data_de_entrega',
  'order_estimated_delivery_date': 'previsao_de_entrega'}, inplace=True)

In [ ]:
# Como ficou
df_orders_copy.columns

Index(['ordem_id', 'cliente_id', 'status_do_pedido', 'data_da_compra',
       'data_da_aprovacao', 'data_de_envio', 'data_de_entrega',
       'previsao_de_entrega'],
      dtype='object')

In [ ]:
df_orders_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ordem_id             99441 non-null  object
 1   cliente_id           99441 non-null  object
 2   status_do_pedido     99441 non-null  object
 3   data_da_compra       99441 non-null  object
 4   data_da_aprovacao    99281 non-null  object
 5   data_de_envio        97658 non-null  object
 6   data_de_entrega      96476 non-null  object
 7   previsao_de_entrega  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

**Renomear as colunas de texto**

**Coluna: status_do_pedido**

In [ ]:
# Quantas vezes aparece cada palavra
df_orders_copy['status_do_pedido'].value_counts()

status_do_pedido
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [ ]:
# Criando o dicionário para substituir os nomes
status = {'delivered': 'Entregue',
                'shipped': 'Enviado',
                'canceled': 'Cancelado',
                'unavailable': 'Indisponível',
                'invoiced': 'Faturado',
                'processing': 'Processando',
                'created': 'Criado',
                'approved': 'Aprovado'}

In [ ]:
# Substituir os atributos usando replace()
df_orders_copy['status_do_pedido'] = df_orders_copy['status_do_pedido'].replace(status)

In [ ]:
# Como ficou agora
df_orders_copy['status_do_pedido'].value_counts()

status_do_pedido
Entregue        96478
Enviado          1107
Cancelado         625
Indisponível      609
Faturado          314
Processando       301
Criado              5
Aprovado            2
Name: count, dtype: int64

**Tratamento de dados faltantes**

In [ ]:
# Dados faltantes
df_orders_copy.isna().sum()

ordem_id                  0
cliente_id                0
status_do_pedido          0
data_da_compra            0
data_da_aprovacao       160
data_de_envio          1783
data_de_entrega        2965
previsao_de_entrega       0
dtype: int64

Como os dados faltantes são de datas, então provavelmente ficam dependentes do status do pedido. Por exemplo, não há como registrar o envio para a logística se o pagamento ainda não foi aprovado. Portanto, deixarei como está porque isso não vai interferir na análise.

**Tratamento de valores duplicados**

In [ ]:
# Há valores duplicados?
linhas_duplas = df_orders_copy[df_orders_copy.duplicated(['ordem_id'], keep=False)]
if not linhas_duplas.empty:
    print('Há valores duplicados:')
    display(linhas_duplas)
else:
    print('Não há valores duplicados.')

Não há valores duplicados.

**Mudando o formato das colunas**

In [ ]:
# Tipo das colunas
df_orders_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ordem_id             99441 non-null  object
 1   cliente_id           99441 non-null  object
 2   status_do_pedido     99441 non-null  object
 3   data_da_compra       99441 non-null  object
 4   data_da_aprovacao    99281 non-null  object
 5   data_de_envio        97658 non-null  object
 6   data_de_entrega      96476 non-null  object
 7   previsao_de_entrega  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

**Colunas de data**

In [ ]:
# 'data_da_compra'
df_orders_copy['data_da_compra'] = pd.to_datetime(df_orders_copy['data_da_compra'], format='mixed', dayfirst=True)
# data_da_aprovacao
df_orders_copy['data_da_aprovacao'] = pd.to_datetime(df_orders_copy['data_da_aprovacao'], format='mixed', dayfirst=True)
# envio_para_logistica
df_orders_copy['data_de_envio'] = pd.to_datetime(df_orders_copy['data_de_envio'], format='mixed', dayfirst=True)
# envio_para_cliente
df_orders_copy['data_de_entrega'] = pd.to_datetime(df_orders_copy['data_de_entrega'], format='mixed', dayfirst=True)
# previsao_de_entrega
df_orders_copy['previsao_de_entrega'] = pd.to_datetime(df_orders_copy['previsao_de_entrega'], format='mixed', dayfirst=True)

In [ ]:
# Como ficou
df_orders_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ordem_id             99441 non-null  object
 1   cliente_id           99441 non-null  object
 2   status_do_pedido     99441 non-null  object
 3   data_da_compra       99441 non-null  datetime64[ns]
 4   data_da_aprovacao    99281 non-null  datetime64[ns]
 5   data_de_envio        97658 non-null  datetime64[ns]
 6   data_de_entrega      96476 non-null  datetime64[ns]
 7   previsao_de_entrega  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

As colunas de data que estavam como tipo 'object' (texto) agora estão em formato 'datetime64[ns]' (data e hora).

**Criando novas colunas**

As colunas abaixo serão criadas para calcular médias, totais, etc.

In [ ]:
# Processamento do pedido = data_de_envio - data_da_aprovacao
df_orders_copy['processamento_do_pedido'] = (df_orders_copy['data_de_envio'] - df_orders_copy['data_da_aprovacao']).dt.days

In [ ]:
# Dias para entregar = data_de_entrega - data_de_envio
df_orders_copy['dias_para_entregar'] = (df_orders_copy['data_de_entrega'] - df_orders_copy['data_de_envio']).dt.days

In [ ]:
# Atraso nas entregas = previsao_de_entrega - data_de_entrega
df_orders_copy['dias_de_atraso'] = (df_orders_copy['previsao_de_entrega'] - df_orders_copy['data_de_entrega']).dt.days

As colunas abaixo serão criadas para analisar sazonalidades, médias, totais, etc, filtrando por data.

In [ ]:
# Crie a coluna 'dia da compra'
df_orders_copy['dia_comp'] = df_orders_copy['data_da_compra'].dt.day

In [ ]:
# Crie a coluna 'mês da compra'
df_orders_copy['mes_comp'] = df_orders_copy['data_da_compra'].dt.month

In [ ]:
# Crie a coluna 'ano da compra'
df_orders_copy['ano_comp'] = df_orders_copy['data_da_compra'].dt.year

A coluna abaixo será criada para calcular a média de dias para aprovação dos pagamentos

In [ ]:
# Crie a coluna de dias para a aprovação do pagamento
df_orders_copy['dias_para_aprovacao'] = (df_orders_copy['data_da_aprovacao'] - df_orders_copy['data_da_compra']).dt.days

In [ ]:
df_orders_copy.head()

,ordem_id,cliente_id,status_do_pedido,data_da_compra,data_da_aprovacao,data_de_envio,data_de_entrega,previsao_de_entrega,processamento_do_pedido,dias_para_entregar,dias_de_atraso,dia_comp,mes_comp,ano_comp,dias_para_aprovacao
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,Entregue,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2.0,6.0,7.0,2,10,2017,0.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,Entregue,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,0.0,12.0,5.0,24,7,2018,1.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,Entregue,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0.0,9.0,17.0,8,8,2018,0.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,Entregue,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,3.0,9.0,12.0,18,11,2017,0.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,Entregue,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,0.0,1.0,9.0,13,2,2018,0.0

In [ ]:
# Número de linhas e colunas
df_orders_copy.shape

(99441, 15)

Foram criadas 10 novas colunas.

In [ ]:
# Salvar o dataframe como csv
# df_orders_copy.to_csv('/content/drive/MyDrive/Banco de dados/Olist/pedidos.csv', index=False, encoding='latin1')

###**Tabela: olist_order_items_dataset**

In [ ]:
# Mostrar as 5 primeiras linhas
df_order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [ ]:
# Número de linhas e colunas
df_order_items.shape

(112650, 7)

In [ ]:
# Nomes das variáveis
df_order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [ ]:
# Informações sobre os tipos de dados
df_order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [ ]:
# Criar uma cópia
df_order_items_copy = df_order_items.copy()

In [ ]:
# Remover espaços iniciais e finais de todas as linhas
df_order_items_copy.columns = df_order_items_copy.columns.str.strip()

In [ ]:
# Colunas da tabela
df_order_items_copy.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [ ]:
# Renomeando colunas
df_order_items_copy.rename(columns=
 {'order_id':'ordem_id',
  'order_item_id':'qtde_itens',
  'product_id':'produto_id',
  'seller_id':'vendedor_id',
  'shipping_limit_date':'data_limite',
  'price':'preço_unitário',
  'freight_value': 'valor_frete'}, inplace=True)

In [ ]:
# Como ficou
df_order_items_copy.columns

Index(['ordem_id', 'qtde_itens', 'produto_id', 'vendedor_id', 'data_limite',
       'preço_unitário', 'valor_frete'],
      dtype='object')

In [ ]:
df_order_items_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ordem_id        112650 non-null  object
 1   qtde_itens      112650 non-null  int64
 2   produto_id      112650 non-null  object
 3   vendedor_id     112650 non-null  object
 4   data_limite     112650 non-null  object
 5   preço_unitário  112650 non-null  float64
 6   valor_frete     112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

**Tratamento de dados faltantes**

In [ ]:
# Dados faltantes
df_order_items_copy.isna().sum()

ordem_id          0
qtde_itens        0
produto_id        0
vendedor_id       0
data_limite       0
preço_unitário    0
valor_frete       0
dtype: int64

**Tratamento de valores duplicados**

In [ ]:
# Há valores duplicados?
linhas_duplas = df_order_items_copy[df_order_items_copy.duplicated(['ordem_id'], keep=False)]
if not linhas_duplas.empty:
    print('Há valores duplicados:')
    display(linhas_duplas)
else:
    print('Não há valores duplicados.')

Há valores duplicados:

,ordem_id,qtde_itens,produto_id,vendedor_id,data_limite,preço_unitário,valor_frete
13,0008288aa423d2a3f00fcb17cd7d8719,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37
14,0008288aa423d2a3f00fcb17cd7d8719,2,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37
32,00143d0f86d6fbd9f9b38ab440ac16f5,1,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10
33,00143d0f86d6fbd9f9b38ab440ac16f5,2,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10
34,00143d0f86d6fbd9f9b38ab440ac16f5,3,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10
...,...,...,...,...,...,...,...
112635,fff8287bbae429a99bb7e8c21d151c41,2,bee2e070c39f3dd2f6883a17a5f0da45,4e922959ae960d389249c378d1c939f5,2018-03-27 12:29:22,180.00,48.14
112640,fffb9224b6fc7c43ebb0904318b10b5f,1,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112641,fffb9224b6fc7c43ebb0904318b10b5f,2,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112642,fffb9224b6fc7c43ebb0904318b10b5f,3,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112643,fffb9224b6fc7c43ebb0904318b10b5f,4,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19

Há valores duplicados, porém essa é a tabela de itens de pedidos então os produtos se repetem.

**Mudando o formato das colunas**

In [ ]:
# Tipo das colunas
df_order_items_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ordem_id        112650 non-null  object
 1   qtde_itens      112650 non-null  int64
 2   produto_id      112650 non-null  object
 3   vendedor_id     112650 non-null  object
 4   data_limite     112650 non-null  object
 5   preço_unitário  112650 non-null  float64
 6   valor_frete     112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

**Colunas de data**

In [ ]:
# 'data_limite'
df_order_items_copy['data_limite'] = pd.to_datetime(df_order_items_copy['data_limite'], format='mixed', dayfirst=True)

In [ ]:
# Como ficou
df_order_items_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ordem_id        112650 non-null  object
 1   qtde_itens      112650 non-null  int64
 2   produto_id      112650 non-null  object
 3   vendedor_id     112650 non-null  object
 4   data_limite     112650 non-null  datetime64[ns]
 5   preço_unitário  112650 non-null  float64
 6   valor_frete     112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 6.0+ MB

A coluna 'data_limite', que antes estava como object (texto), agora está no formato datetime64[ns] (data e hora).

**Criando novas colunas**

In [ ]:
# Crie a coluna preço total dos itens
df_order_items_copy['preço_total'] = df_order_items_copy['preço_unitário'] * df_order_items_copy['qtde_itens']

In [ ]:
# Crie a coluna total do pedido
df_order_items_copy['total_do_pedido'] = df_order_items_copy['preço_total'] + df_order_items_copy['valor_frete']

In [ ]:
# Salvar o dataframe como csv
# df_order_items_copy.to_csv('/content/drive/MyDrive/Banco de dados/Olist/itens_de_pedidos.csv', index=False, encoding='latin1')

###**Tabela: olist_products_dataset**

In [ ]:
# Mostrar as 5 primeiras linhas
df_products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [ ]:
# Número de linhas e colunas
df_products.shape

(32951, 9)

In [ ]:
# Nomes das variáveis
df_products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [ ]:
# Informações sobre os tipos de dados
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [ ]:
# Criar uma cópia
df_products_copy = df_products.copy()

In [ ]:
# Remover espaços iniciais e finais de toda a tabela
df_products_copy.columns = df_products_copy.columns.str.strip()

In [ ]:
# Renomeando colunas
df_products_copy.rename(columns=
 {'product_id':'produto_id',
  'product_category_name':'categoria',
  'product_name_lenght':'comp_nome',
  'product_description_lenght':'comp_descrição',
  'product_photos_qty':'qtde_fotos',
  'product_weight_g':'peso_gr',
  'product_length_cm': 'comprimento_cm',
  'product_height_cm': 'altura_cm',
  'product_width_cm': 'largura_cm'}, inplace=True)

**Renomeando colunas de texto**

In [ ]:
df_products_copy.columns

Index(['produto_id', 'categoria', 'comp_nome', 'comp_descrição', 'qtde_fotos',
       'peso_gr', 'comprimento_cm', 'altura_cm', 'largura_cm'],
      dtype='object')

**Coluna: categoria**

In [ ]:
# Valores únicos
df_products_copy['categoria'].unique()

array(['perfumaria', 'artes', 'esporte_lazer', 'bebes',
       'utilidades_domesticas', 'instrumentos_musicais', 'cool_stuff',
       'moveis_decoracao', 'eletrodomesticos', 'brinquedos',
       'cama_mesa_banho', 'construcao_ferramentas_seguranca',
       'informatica_acessorios', 'beleza_saude', 'malas_acessorios',
       'ferramentas_jardim', 'moveis_escritorio', 'automotivo',
       'eletronicos', 'fashion_calcados', 'telefonia', 'papelaria',
       'fashion_bolsas_e_acessorios', 'pcs', 'casa_construcao',
       'relogios_presentes', 'construcao_ferramentas_construcao',
       'pet_shop', 'eletroportateis', 'agro_industria_e_comercio', nan,
       'moveis_sala', 'sinalizacao_e_seguranca', 'climatizacao',
       'consoles_games', 'livros_interesse_geral',
       'construcao_ferramentas_ferramentas',
       'fashion_underwear_e_moda_praia', 'fashion_roupa_masculina',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'industria_comercio_e_negocios', 'telefonia_fixa',
       'construcao_ferramentas_iluminacao', 'livros_tecnicos',
       'eletrodomesticos_2', 'artigos_de_festas', 'bebidas',
       'market_place', 'la_cuisine', 'construcao_ferramentas_jardim',
       'fashion_roupa_feminina', 'casa_conforto', 'audio',
       'alimentos_bebidas', 'musica', 'alimentos',
       'tablets_impressao_imagem', 'livros_importados',
       'portateis_casa_forno_e_cafe', 'fashion_esporte',
       'artigos_de_natal', 'fashion_roupa_infanto_juvenil',
       'dvds_blu_ray', 'artes_e_artesanato', 'pc_gamer', 'moveis_quarto',
       'cine_foto', 'fraldas_higiene', 'flores', 'casa_conforto_2',
       'portateis_cozinha_e_preparadores_de_alimentos',
       'seguros_e_servicos', 'moveis_colchao_e_estofado',
       'cds_dvds_musicais'], dtype=object)

In [ ]:
# Criando o dicionário para renomear o conteúdo das colunas com maiúsculas, removendo o '_' e colocando acentos
categorias = {
    'perfumaria': 'Perfumaria',
    'artes': 'Artes',
    'esporte_lazer': 'Esporte e Lazer',
    'bebes': 'Bebês',
    'utilidades_domesticas': 'Utilidades Domésticas',
    'instrumentos_musicais': 'Instrumentos Musicais',
    'cool_stuff': 'Coisas legais',
    'moveis_decoracao': 'Móveis e Decoração',
    'eletrodomesticos': 'Eletrodomésticos',
    'brinquedos': 'Brinquedos',
    'cama_mesa_banho': 'Cama, Mesa e Banho',
    'construcao_ferramentas_seguranca': 'Construção, Ferramentas e Segurança',
    'informatica_acessorios': 'Informática e Acessórios',
    'beleza_saude': 'Beleza e Saúde',
    'malas_acessorios': 'Malas e Acessórios',
    'ferramentas_jardim': 'Ferramentas de Jardim',
    'moveis_escritorio': 'Móveis de Escritório',
    'automotivo': 'Automotivo',
    'eletronicos': 'Eletrônicos',
    'fashion_calcados': 'Fashion Calçados',
    'telefonia': 'Telefonia',
    'papelaria': 'Papelaria',
    'fashion_bolsas_e_acessorios': 'Fashion, Bolsas e Acessórios',
    'pcs': 'PCs',
    'casa_construcao': 'Casa e Construção',
    'relogios_presentes': 'Relógios e Presentes',
    'construcao_ferramentas_construcao': 'Construção e Ferramentas',
    'pet_shop': 'Pet Shop',
    'eletroportateis': 'Eletroportáteis',
    'agro_industria_e_comercio': 'Agro, Indústria e Comércio',
    'moveis_sala': 'Móveis de Sala',
    'sinalizacao_e_seguranca': 'Sinalização e Segurança',
    'climatizacao': 'Climatização',
    'consoles_games': 'Consoles e Games',
    'livros_interesse_geral': 'Livros de Interesse Geral',
    'construcao_ferramentas_ferramentas': 'Ferramentas de Construção',
    'fashion_underwear_e_moda_praia': 'Moda Íntima e Praia',
    'fashion_roupa_masculina': 'Moda Masculina',
    'moveis_cozinha_area_de_servico_jantar_e_jardim': 'Móveis de Cozinha e Jardim',
    'industria_comercio_e_negocios': 'Indústria e Comércio',
    'telefonia_fixa': 'Telefonia Fixa',
    'construcao_ferramentas_iluminacao': 'Construção e Iluminação',
    'livros_tecnicos': 'Livros Técnicos',
    'eletrodomesticos_2': 'Eletrodomésticos (Tipo 2)',
    'artigos_de_festas': 'Artigos de Festas',
    'bebidas': 'Bebidas',
    'market_place': 'Marketplace',
    'la_cuisine': 'La Cuisine',
    'construcao_ferramentas_jardim': 'Construção e Jardim',
    'fashion_roupa_feminina': 'Moda Feminina',
    'casa_conforto': 'Casa e Conforto',
    'audio': 'Áudio',
    'alimentos_bebidas': 'Alimentos e Bebidas',
    'musica': 'Música',
    'alimentos': 'Alimentos',
    'tablets_impressao_imagem': 'Tablets e Imagem',
    'livros_importados': 'Livros Importados',
    'portateis_casa_forno_e_cafe': 'Portáteis de Cozinha',
    'fashion_esporte': 'Moda Esportiva',
    'artigos_de_natal': 'Artigos de Natal',
    'fashion_roupa_infanto_juvenil': 'Moda Infantil',
    'dvds_blu_ray': 'DVDs e Blu-ray',
    'artes_e_artesanato': 'Artes e Artesanato',
    'pc_gamer': 'PC Gamer',
    'moveis_quarto': 'Móveis de Quarto',
    'cine_foto': 'Cine e Foto',
    'fraldas_higiene': 'Fraldas e Higiene',
    'flores': 'Flores',
    'casa_conforto_2': 'Casa e Conforto (Tipo 2)',
    'portateis_cozinha_e_preparadores_de_alimentos': 'Portáteis de Cozinha',
    'seguros_e_servicos': 'Seguros e Serviços',
    'moveis_colchao_e_estofado': 'Móveis e Estofados',
    'cds_dvds_musicais': 'CDs e DVDs Musicais'}

In [ ]:
# Tratando valores nulos NaNs para evitar erros
df_products_copy['categoria'] = df_products_copy['categoria'].fillna('Não Informado')

In [ ]:
# Substituir o dicionário criado pelo conteúdo da coluna usando map()
df_products_copy['categoria'] = df_products_copy['categoria'].map(categorias).fillna(df_products_copy['categoria'])

In [ ]:
# Substituindo os _ por espaços
df_products_copy['categoria'] = df_products_copy['categoria'].str.replace('_', ' ').str.capitalize()

In [ ]:
# Como ficou
df_products_copy['categoria'].unique()

array(['Perfumaria', 'Artes', 'Esporte e lazer', 'Bebês',
       'Utilidades domésticas', 'Instrumentos musicais', 'Coisas legais',
       'Móveis e decoração', 'Eletrodomésticos', 'Brinquedos',
       'Cama, mesa e banho', 'Construção, ferramentas e segurança',
       'Informática e acessórios', 'Beleza e saúde', 'Malas e acessórios',
       'Ferramentas de jardim', 'Móveis de escritório', 'Automotivo',
       'Eletrônicos', 'Fashion calçados', 'Telefonia', 'Papelaria',
       'Fashion, bolsas e acessórios', 'Pcs', 'Casa e construção',
       'Relógios e presentes', 'Construção e ferramentas', 'Pet shop',
       'Eletroportáteis', 'Agro, indústria e comércio', 'Não informado',
       'Móveis de sala', 'Sinalização e segurança', 'Climatização',
       'Consoles e games', 'Livros de interesse geral',
       'Ferramentas de construção', 'Moda íntima e praia',
       'Moda masculina', 'Móveis de cozinha e jardim',
       'Indústria e comércio', 'Telefonia fixa',
       'Construção e iluminação', 'Livros técnicos',
       'Eletrodomésticos (tipo 2)', 'Artigos de festas', 'Bebidas',
       'Marketplace', 'La cuisine', 'Construção e jardim',
       'Moda feminina', 'Casa e conforto', 'Áudio', 'Alimentos e bebidas',
       'Música', 'Alimentos', 'Tablets e imagem', 'Livros importados',
       'Portáteis de cozinha', 'Moda esportiva', 'Artigos de natal',
       'Moda infantil', 'Dvds e blu-ray', 'Artes e artesanato',
       'Pc gamer', 'Móveis de quarto', 'Cine e foto', 'Fraldas e higiene',
       'Flores', 'Casa e conforto (tipo 2)', 'Seguros e serviços',
       'Móveis e estofados', 'Cds e dvds musicais'], dtype=object)

In [ ]:
# Verificar quantos dados faltantes ainda restam
df_products_copy.isna().sum()

produto_id          0
categoria           0
comp_nome         610
comp_descrição    610
qtde_fotos        610
peso_gr             2
comprimento_cm      2
altura_cm           2
largura_cm          2
dtype: int64

In [ ]:
# Substituir valores faltantes por zero
df_products_copy = df_products_copy.fillna(0)

In [ ]:
# E agora?
df_products_copy.isna().sum()

produto_id        0
categoria         0
comp_nome         0
comp_descrição    0
qtde_fotos        0
peso_gr           0
comprimento_cm    0
altura_cm         0
largura_cm        0
dtype: int64

Como são apenas as características dos produtos que não são importantes para a análise, então substituí por zero.

In [ ]:
# Informações sobre os tipos de dados
df_products_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   produto_id      32951 non-null  object
 1   categoria       32951 non-null  object
 2   comp_nome       32951 non-null  float64
 3   comp_descrição  32951 non-null  float64
 4   qtde_fotos      32951 non-null  float64
 5   peso_gr         32951 non-null  float64
 6   comprimento_cm  32951 non-null  float64
 7   altura_cm       32951 non-null  float64
 8   largura_cm      32951 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [ ]:
# Verificar se há valores duplicados
linhas_duplas = df_products_copy[df_products_copy.duplicated(['produto_id'], keep=False)]
if not linhas_duplas.empty:
    print('Há valores duplicados:')
    display(linhas_duplas)
else:
    print('Não há valores duplicados.')

Não há valores duplicados.

In [ ]:
# Tabela limpa
df_products_copy.head()

,produto_id,categoria,comp_nome,comp_descrição,qtde_fotos,peso_gr,comprimento_cm,altura_cm,largura_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,Perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,Artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,Esporte e lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,Bebês,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,Utilidades domésticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [ ]:
# Antes da limpeza
df_products.shape

(32951, 9)

In [ ]:
# Depois da limpeza
df_products_copy.shape

(32951, 9)

Nem uma única linha foi excluída na tabela.

In [ ]:
# Salvar o dataframe como csv
# df_products_copy.to_csv('/content/drive/MyDrive/Banco de dados/Olist/produtos.csv', index=False, encoding='latin1')

###**Tabela: df_customer**

In [ ]:
# Mostrar as 5 primeiras linhas
df_customer.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [ ]:
# Número de linhas e colunas
df_customer.shape

(99441, 5)

In [ ]:
# Nomes das variáveis
df_customer.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [ ]:
# Informações sobre os tipos de dados
df_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [ ]:
# Criar uma cópia
df_customer_copy = df_customer.copy()

In [ ]:
# Remover espaços iniciais e finais
df_customer_copy.columns = df_customer_copy.columns.str.strip()

In [ ]:
df_customer_copy.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [ ]:
# Renomeando colunas
df_customer_copy.rename(columns=
 {'customer_id':'cliente_id',
  'customer_unique_id':'cliente_id_unico',
  'customer_zip_code_prefix':'CEP',
  'customer_city':'Cidade',
  'customer_state':'Estado'}, inplace=True)

**Renomeando colunas de texto**

In [ ]:
df_customer_copy.columns

Index(['cliente_id', 'cliente_id_unico', 'CEP', 'Cidade', 'Estado'], dtype='object')

**Coluna: Cidade**

In [ ]:
# Valores únicos
df_customer_copy['Cidade'].count()

np.int64(99441)

In [ ]:
# Colocando maiúsculas no início de cada palavra
df_customer_copy['Cidade'] = df_customer_copy['Cidade'].str.title()

In [ ]:
df_customer_copy['Cidade']

0                       Franca
1        Sao Bernardo Do Campo
2                    Sao Paulo
3              Mogi Das Cruzes
4                     Campinas
                 ...
99436                Sao Paulo
99437          Taboao Da Serra
99438                Fortaleza
99439                   Canoas
99440                    Cotia
Name: Cidade, Length: 99441, dtype: object

Como são muitos registros de cidades, então apenas coloquei maiúscula no início de cada palavra. Não foi colocado acentos.

In [ ]:
# Verificar dados faltantes
df_customer_copy.isna().sum()

cliente_id          0
cliente_id_unico    0
CEP                 0
Cidade              0
Estado              0
dtype: int64

In [ ]:
# Informações sobre os tipos de dados
df_customer_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cliente_id        99441 non-null  object
 1   cliente_id_unico  99441 non-null  object
 2   CEP               99441 non-null  int64
 3   Cidade            99441 non-null  object
 4   Estado            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [ ]:
# Verificar se há valores duplicados
linhas_duplas = df_customer_copy[df_customer_copy.duplicated(['cliente_id'], keep=False)]
if not linhas_duplas.empty:
    print('Há valores duplicados:')
    display(linhas_duplas)
else:
    print('Não há valores duplicados.')

Não há valores duplicados.

In [ ]:
# Tabela limpa
df_customer_copy.head()

,cliente_id,cliente_id_unico,CEP,Cidade,Estado
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,Franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,Sao Bernardo Do Campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,Sao Paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,Mogi Das Cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,Campinas,SP

In [ ]:
# Antes da limpeza
df_customer.shape

(99441, 5)

In [ ]:
# Depois da limpeza
df_customer_copy.shape

(99441, 5)

Nem uma única linha foi excluída na tabela.

In [ ]:
# Salvar o dataframe como csv
# df_customer_copy.to_csv('/content/drive/MyDrive/Banco de dados/Olist/clientes.csv', index=False, encoding='latin1')

###**Tabela: df_payments**

In [ ]:
# Mostrar as 5 primeiras linhas
df_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [ ]:
# Número de linhas e colunas
df_payments.shape

(103886, 5)

In [ ]:
# Nomes das variáveis
df_payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [ ]:
# Informações sobre os tipos de dados
df_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [ ]:
# Criar uma cópia
df_payments_copy = df_payments.copy()

In [ ]:
# Remover espaços iniciais e finais
df_payments_copy.columns = df_payments_copy.columns.str.strip()

In [ ]:
df_payments_copy.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [ ]:
# Renomeando colunas
df_payments_copy.rename(columns=
 {'order_id':'ordem_id',
  'payment_sequential':'qtde_formas',
  'payment_type':'forma_de_pag',
  'payment_installments':'parcelas',
  'payment_value':'valor'}, inplace=True)

**Renomeando colunas de texto**

In [ ]:
df_payments_copy.columns

Index(['ordem_id', 'qtde_formas', 'forma_de_pag', 'parcelas', 'valor'], dtype='object')

**Coluna: forma_de_pag**

In [ ]:
# Valores únicos
df_payments_copy['forma_de_pag'].unique()

array(['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined'],
      dtype=object)

In [ ]:
# Criando o dicionário para substituir
pag = {'credit_card': 'Cartão de crédito',
                'boleto': 'Boleto bancário',
                'voucher': 'Vale-presente',
                'debit_card': 'Cartão de débito',
                'not_defined': 'Não definido'}

In [ ]:
# Substituir os atributos usando replace()
df_payments_copy['forma_de_pag'] = df_payments_copy['forma_de_pag'].replace(pag)

In [ ]:
# Como ficou agora
df_payments_copy['forma_de_pag'].value_counts()

forma_de_pag
Cartão de crédito    76795
Boleto bancário      19784
Vale-presente         5775
Cartão de débito      1529
Não definido             3
Name: count, dtype: int64

Apenas 3 valores não definidos que não irão interferir na análise.

In [ ]:
# Informações sobre os tipos de dados
df_payments_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ordem_id      103886 non-null  object
 1   qtde_formas   103886 non-null  int64
 2   forma_de_pag  103886 non-null  object
 3   parcelas      103886 non-null  int64
 4   valor         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

Não precisa mudar o formato de nenhuma coluna.

In [ ]:
# Verificar se há valores duplicados
linhas_duplas = df_payments_copy[df_payments_copy.duplicated(['ordem_id'], keep=False)]
if not linhas_duplas.empty:
    print('Há valores duplicados:')
    display(linhas_duplas)
else:
    print('Não há valores duplicados.')

Há valores duplicados:

,ordem_id,qtde_formas,forma_de_pag,parcelas,valor
25,5cfd514482e22bc992e7693f0e3e8df7,2,Vale-presente,1,45.17
35,b2bb080b6bc860118a246fd9b6fad6da,1,Cartão de crédito,1,173.84
75,3689194c14ad4e2e7361ebd1df0e77b0,2,Vale-presente,1,57.53
84,723e462ce1ee50e024887c0b403130f3,1,Cartão de crédito,1,13.80
102,21b8b46679ea6482cbf911d960490048,2,Vale-presente,1,43.12
...,...,...,...,...,...
103778,fd86c80924b4be8fb7f58c4ecc680dae,1,Cartão de crédito,1,76.10
103817,6d4616de4341417e17978fe57aec1c46,1,Cartão de crédito,1,19.18
103860,31bc09fdbd701a7a4f9b55b5955b8687,6,Vale-presente,1,77.99
103869,c9b01bef18eb84888f0fd071b8413b38,1,Cartão de crédito,6,238.16
103874,d41f1036712e18ee525939d08b7a1c98,1,Cartão de crédito,1,3.57

Há valores duplicados porque muitos clientes fizeram mais de uma compra. Os dados não devem ser excluídos.

In [ ]:
# Verificar dados faltantes
df_payments_copy.isna().sum()

ordem_id        0
qtde_formas     0
forma_de_pag    0
parcelas        0
valor           0
dtype: int64

In [ ]:
# Antes da limpeza
df_payments.shape

(103886, 5)

In [ ]:
# Depois da limpeza
df_payments_copy.shape

(103886, 5)

Nem uma única linha foi excluída na tabela.

In [ ]:
# Salvar o dataframe como csv
# df_payments_copy.to_csv('/content/drive/MyDrive/Banco de dados/Olist/pagamentos.csv', index=False, encoding='latin1')

###**Tabela: df_sellers**

In [ ]:
# Criar uma cópia
df_sellers_copy = df_sellers.copy()

In [ ]:
# Mostrar as 5 primeiras linhas
df_sellers_copy.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [ ]:
# Número de linhas e colunas
df_sellers_copy.shape

(3095, 4)

In [ ]:
# Nomes das variáveis
df_sellers_copy.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [ ]:
# Informações sobre os tipos de dados
df_sellers_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [ ]:
# Remover espaços iniciais e finais
df_sellers_copy.columns = df_sellers_copy.columns.str.strip()

In [ ]:
df_sellers_copy.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [ ]:
# Renomeando colunas
df_sellers_copy.rename(columns=
 {'seller_id':'vendedor_id',
  'seller_zip_code_prefix':'CEP',
  'seller_city':'Cidade',
  'seller_state':'Estado'}, inplace=True)

**Renomeando colunas de texto**

In [ ]:
df_sellers_copy.columns

Index(['vendedor_id', 'CEP', 'Cidade', 'Estado'], dtype='object')

**Coluna: Cidade_vendedor**

In [ ]:
# Valores únicos
df_sellers_copy['Cidade'].count()

np.int64(3095)

In [ ]:
# Colocando maiúsculas no início de cada palavra
df_sellers_copy['Cidade'] = df_sellers_copy['Cidade'].str.title()

In [ ]:
df_sellers_copy['Cidade']

0                Campinas
1              Mogi Guacu
2          Rio De Janeiro
3               Sao Paulo
4       Braganca Paulista
              ...
3090              Sarandi
3091              Palhoca
3092            Sao Paulo
3093              Pelotas
3094              Taubate
Name: Cidade, Length: 3095, dtype: object

Como são muitos registros de cidades, então apenas coloquei maiúscula no início de cada palavra. Não foi colocado acentos.

In [ ]:
# Verificar dados faltantes
df_sellers_copy.isna().sum()

vendedor_id    0
CEP            0
Cidade         0
Estado         0
dtype: int64

In [ ]:
# Informações sobre os tipos de dados
df_sellers_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   vendedor_id  3095 non-null   object
 1   CEP          3095 non-null   int64
 2   Cidade       3095 non-null   object
 3   Estado       3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

Não precisa mudar o formato de nenhuma coluna.

In [ ]:
# Verificar se há valores duplicados
linhas_duplas = df_sellers_copy[df_sellers_copy.duplicated(['vendedor_id'], keep=False)]
if not linhas_duplas.empty:
    print('Há valores duplicados:')
    display(linhas_duplas)
else:
    print('Não há valores duplicados.')

Não há valores duplicados.

Se não há valores duplicados então quer dizer que nesta tabela contém apenas os identificadores únicos de cada vendedor.

In [ ]:
# Tabela limpa
df_sellers_copy.head()

                        vendedor_id    CEP             Cidade Estado
0  3442f8959a84dea7ee197c632cb2df15  13023           Campinas     SP
1  d1b65fc7debc3361ea86b5f14c68d2e2  13844         Mogi Guacu     SP
2  ce3ad9de960102d0677a81f5d0bb7b2d  20031     Rio De Janeiro     RJ
3  c0f3eea2e14555b6faeea3dd58c1b1c3   4195          Sao Paulo     SP
4  51a04a8a6bdcb23deccc82b0b80742cf  12914  Braganca Paulista     SP

In [ ]:
# Antes da limpeza
df_sellers.shape

(3095, 4)

In [ ]:
# Depois da limpeza
df_sellers_copy.shape

(3095, 4)

Nem uma única linha foi excluída na tabela.

In [ ]:
# Salvar o dataframe como csv
# df_sellers_copy.to_csv('/content/drive/MyDrive/Banco de dados/Olist/vendedores.csv', index=False, encoding='utf-8')

###**Tabela: df_geolocation**

In [ ]:
# Criar uma cópia
df_geolocation_copy = df_geolocation.copy()

In [ ]:
# Remover espaços iniciais e finais de todas as linhas
df_geolocation_copy.columns = df_geolocation_copy.columns.str.strip()

In [ ]:
# Colunas da tabela
df_geolocation_copy.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='object')

In [ ]:
# Renomeando colunas
df_geolocation_copy.rename(columns=
 {'geolocation_zip_code_prefix':'CEP',
  'geolocation_lat':'latitude_geo',
  'geolocation_lng':'longitude_geo',
  'geolocation_city':'Cidade',
  'geolocation_state':'Estado'}, inplace=True)

In [ ]:
# Como ficou
df_geolocation_copy.columns

Index(['CEP', 'latitude_geo', 'longitude_geo', 'Cidade', 'Estado'], dtype='object')

In [ ]:
df_geolocation_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   CEP            1000163 non-null  int64
 1   latitude_geo   1000163 non-null  float64
 2   longitude_geo  1000163 non-null  float64
 3   Cidade         1000163 non-null  object
 4   Estado         1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

Não precisa mudar o tipo das colunas.

**Renomear as colunas de texto**

**Coluna: status_do_pedido**

In [ ]:
# Quantas vezes aparece cada palavra
df_geolocation_copy['Cidade'].value_counts()

Cidade
sao paulo         135800
rio de janeiro     62151
belo horizonte     27805
são paulo          24918
curitiba           16593
                   ...
tres irmaos            1
morro chato            1
valao do barro         1
jordanésia             1
são valentim           1
Name: count, Length: 8011, dtype: int64

In [ ]:
# Colocando maiúsculas no início de cada palavra
df_geolocation_copy['Cidade'] = df_geolocation_copy['Cidade'].str.title()

In [ ]:
# Como ficou agora
df_geolocation_copy['Cidade'].value_counts()

Cidade
Sao Paulo         135800
Rio De Janeiro     62151
Belo Horizonte     27805
São Paulo          24918
Curitiba           16593
                   ...
Tres Irmaos            1
Morro Chato            1
Valao Do Barro         1
Jordanésia             1
São Valentim           1
Name: count, Length: 8011, dtype: int64

**Tratamento de dados faltantes**

In [ ]:
# Dados faltantes
df_geolocation_copy.isna().sum()

CEP              0
latitude_geo     0
longitude_geo    0
Cidade           0
Estado           0
dtype: int64

**Tratamento de valores duplicados**

Não precisa tratar valores duplicados nesta tabela.

**Mudando o formato das colunas**

In [ ]:
# Tipo das colunas
df_geolocation_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   CEP            1000163 non-null  int64
 1   latitude_geo   1000163 non-null  float64
 2   longitude_geo  1000163 non-null  float64
 3   Cidade         1000163 non-null  object
 4   Estado         1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [ ]:
# Verificar se há valores duplicados
linhas_duplas = df_geolocation_copy[df_geolocation_copy.duplicated(['CEP'], keep=False)]
if not linhas_duplas.empty:
    print('Há valores duplicados:')
    display(linhas_duplas)
else:
    print('Não há valores duplicados.')

Há valores duplicados:

           CEP  latitude_geo  longitude_geo           Cidade Estado
0         1037    -23.545621     -46.639292        Sao Paulo     SP
1         1046    -23.546081     -46.644820        Sao Paulo     SP
2         1046    -23.546129     -46.642951        Sao Paulo     SP
3         1041    -23.544392     -46.639499        Sao Paulo     SP
4         1035    -23.541578     -46.641607        Sao Paulo     SP
...        ...           ...            ...              ...    ...
1000158  99950    -28.068639     -52.010705         Tapejara     RS
1000159  99900    -27.877125     -52.224882   Getulio Vargas     RS
1000160  99950    -28.071855     -52.014716         Tapejara     RS
1000161  99980    -28.388932     -51.846871  David Canabarro     RS
1000162  99950    -28.070104     -52.018658         Tapejara     RS

[999120 rows x 5 columns]

Não precisa mudar o tipo das colunas.

Nessa tabela poderia ter a coluna 'ordem_id' para registrar de onde vieram os pedidos. Assim eu poderia criar um mapa de calor com os dados de latitude e longitude.

In [ ]:
# Tabela limpa
df_geolocation_copy.head()

    CEP  latitude_geo  longitude_geo     Cidade Estado
0  1037    -23.545621     -46.639292  Sao Paulo     SP
1  1046    -23.546081     -46.644820  Sao Paulo     SP
2  1046    -23.546129     -46.642951  Sao Paulo     SP
3  1041    -23.544392     -46.639499  Sao Paulo     SP
4  1035    -23.541578     -46.641607  Sao Paulo     SP

In [ ]:
# Antes da limpeza
df_geolocation.shape

(1000163, 5)

In [ ]:
# Depois da limpeza
df_geolocation_copy.shape

(1000163, 5)

Nem uma única linha foi excluída na tabela.

In [ ]:
# Salvar o dataframe como csv
# df_geolocation_copy.to_csv('/content/drive/MyDrive/Banco de dados/Olist/geolocalizacao.csv', index=False, encoding='utf-8')